//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Users\pan.hejitian\Desktop\PLM\自动截图\csharp尝试\ClassLibrary1\ClassLibrary1\bin\Debug\ClassLibrary1.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: pan.hejitian
//              Version: NX 1946
//              Date: 06-03-2026  (Format: mm-dd-yyyy)
//              Time: 16:30 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class ClassLibrary1
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.FolderSelection filePath;// Block type: NativeFolderBrowser
    private NXOpen.BlockStyler.MultilineString namePatterns;// Block type: Multiline String
    private NXOpen.BlockStyler.MultilineString IDPattern;// Block type: Multiline String
    private NXOpen.BlockStyler.Group group;// Block type: Group
    private NXOpen.BlockStyler.Toggle flagImageOn;// Block type: Toggle
    private NXOpen.BlockStyler.ListBox viewList;// Block type: List Box
    private NXOpen.BlockStyler.Group group0;// Block type: Group
    private NXOpen.BlockStyler.Toggle flagXYZOn;// Block type: Toggle
    private NXOpen.BlockStyler.Enumeration coordinateSelection;// Block type: Enumeration
    
    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public ClassLibrary1()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "ClassLibrary1.dlx";
            theDialog = theUI.CreateDialog(theDlxFileName);
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        ClassLibrary1 theClassLibrary1 = null;
        try
        {
            theClassLibrary1 = new ClassLibrary1();
            // The following method shows the dialog immediately
            theClassLibrary1.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if(theClassLibrary1 != null)
                theClassLibrary1.Dispose();
                theClassLibrary1 = null;
        }
    }
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
     public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
         return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //This method shows the dialog on the screen
    //------------------------------------------------------------------------------
    public NXOpen.UIStyler.DialogResponse Show()
    {
        try
        {
            theDialog.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            filePath = (NXOpen.BlockStyler.FolderSelection)theDialog.TopBlock.FindBlock("filePath");
            namePatterns = (NXOpen.BlockStyler.MultilineString)theDialog.TopBlock.FindBlock("namePatterns");
            IDPattern = (NXOpen.BlockStyler.MultilineString)theDialog.TopBlock.FindBlock("IDPattern");
            group = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group");
            flagImageOn = (NXOpen.BlockStyler.Toggle)theDialog.TopBlock.FindBlock("flagImageOn");
            viewList = (NXOpen.BlockStyler.ListBox)theDialog.TopBlock.FindBlock("viewList");
            group0 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group0");
            flagXYZOn = (NXOpen.BlockStyler.Toggle)theDialog.TopBlock.FindBlock("flagXYZOn");
            coordinateSelection = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("coordinateSelection");
            //------------------------------------------------------------------------------
            //Registration of ListBox specific callbacks
            //------------------------------------------------------------------------------
            //viewList.SetAddHandler(new NXOpen.BlockStyler.ListBox.AddCallback(AddCallback));
            
            //viewList.SetDeleteHandler(new NXOpen.BlockStyler.ListBox.DeleteCallback(DeleteCallback));
            
            //------------------------------------------------------------------------------
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            TraversalConfig config = new TraversalConfig();
            
            config.filePath = filePath.Path;
            
            PropertyList nameProps = namePatterns.GetProperties();
            string[] nameLines = nameProps.GetStrings("String");
            config.namePatterns = nameLines ?? new string[0];
            
            PropertyList idProps = IDPattern.GetProperties();
            string[] idLines = idProps.GetStrings("String");
            config.idPatterns = idLines ?? new string[0];
            
            config.flagImageOn = flagImageOn.GetProperties().GetLogical("Value");
            
            if (config.flagImageOn && viewList != null)
            {
                var selectedItems = viewList.GetSelectedItems();
                PropertyList viewProps = viewList.GetProperties();
                string[] allItems = viewProps.GetStrings("ListItems");
                System.Collections.Generic.List<ImageExporter.SnapViewType> views = 
                    new System.Collections.Generic.List<ImageExporter.SnapViewType>();
                foreach (var item in selectedItems)
                {
                    int index = item.Index;
                    if (index >= 0 && index < allItems.Length)
                    {
                        if (System.Enum.TryParse<ImageExporter.SnapViewType>(allItems[index], out var viewType))
                        {
                            views.Add(viewType);
                        }
                    }
                }
                config.viewList = views.ToArray();
            }
            
            config.flagXYZOn = flagXYZOn.GetProperties().GetLogical("Value");
            
            if (config.flagXYZOn && coordinateSelection != null)
            {
                PropertyList coordProps = coordinateSelection.GetProperties();
                config.coordinateSelection = coordProps.GetString("Value") ?? "ACS";
            }
            
            AssemblyTraverser.Main(config);
        }
        catch (Exception ex)
        {
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    private string[] ParseMultilineString(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return new string[0];
        }
        
        string[] lines = text.Split(new[] { '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);
        System.Collections.Generic.List<string> result = new System.Collections.Generic.List<string>();
        foreach (string line in lines)
        {
            string trimmed = line.Trim();
            if (!string.IsNullOrWhiteSpace(trimmed))
            {
                result.Add(trimmed);
            }
        }
        return result.ToArray();
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb( NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if(block == filePath)
            {
            //---------Enter your code here-----------
            }
            else if(block == namePatterns)
            {
            //---------Enter your code here-----------
            }
            else if(block == IDPattern)
            {
            //---------Enter your code here-----------
            }
            else if(block == flagImageOn)
            {
            //---------Enter your code here-----------
            }
            else if(block == viewList)
            {
            //---------Enter your code here-----------
            }
            else if(block == flagXYZOn)
            {
            //---------Enter your code here-----------
            }
            else if(block == coordinateSelection)
            {
            //---------Enter your code here-----------
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            errorCode = apply_cb();
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    //------------------------------------------------------------------------------
    //ListBox specific callbacks
    //------------------------------------------------------------------------------
    //public int  AddCallback (NXOpen.BlockStyler.ListBox list_box)
    //{
    //}
    
    //public int  DeleteCallback(NXOpen.BlockStyler.ListBox list_box)
    //{
    //}
    
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist =null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }
    
}

